project:
  type: website
  output-dir: docs

website:
  title: "David Martini"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        href: https://mastodon.social/@david_martini
      - icon: twitter
        href: https://twitter.com/David__Martini
format:
  html:
    theme: journal
    css: styles.css

editor: visual

